services:
  sniffnet-docker-novnc: 
    # build with `docker build -t psychowood/sniffnet-docker-novnc .`
    image: psychowood/sniffnet-docker-novnc:latest
    container_name: sniffnet-docker-novnc
    network_mode: host
    environment:
      - WEB_PORT=8088
      # Adjust if you want
      - DISPLAY_WIDTH=1600
      - DISPLAY_HEIGHT=1200
    #If you want to save dumps somewhere persistent, uncomment this and adjust the path
#    volumes:
#      - /tmp:/tmp
    cap_add:
      - NET_ADMIN
      - NET_RAW